// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebControlShoes.Infastructure;

#nullable disable

namespace WebControlShoes.Infastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230321182525_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebControlShoes.Domain.Entities.LineaProduccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Nrolinea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Nrolinea");

                    b.ToTable("LineasProduccion", (string)null);
                });

            modelBuilder.Entity("WebControlShoes.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("OrdenProduccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("NameUsuario");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Alerta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LimiteAviso")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrdenProduccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Reinicio")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Reinicio");

                    b.HasIndex("OrdenProduccionId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Colour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasAlternateKey("CodigoColor");

                    b.ToTable("Colours", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Defecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IncidenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoDefecto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenciaId");

                    b.ToTable("Defectos", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Incidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hora")
                        .HasColumnType("int");

                    b.Property<Guid?>("JornadaLaboralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Pie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JornadaLaboralId");

                    b.ToTable("Incidencia", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.JornadaLaboral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasMaxLength(255)
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTurno")
                        .HasColumnType("int");

                    b.Property<Guid?>("OrdenProduccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalPrimera")
                        .HasColumnType("int");

                    b.Property<int>("TotalSegunda")
                        .HasColumnType("int");

                    b.Property<Guid>("TurnoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrdenProduccionId");

                    b.HasIndex("TurnoId");

                    b.ToTable("JornadasLaborales", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LimiteInferiorObservado")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("LimiteInferiorReproceso")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("LimiteSuperiorObservado")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("LimiteSuperiorReproceso")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Sku");

                    b.ToTable("Modelos", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.OrdenProduccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoOP")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ColourId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LineaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModeloId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("CodigoOP");

                    b.HasIndex("ColourId");

                    b.HasIndex("LineaId");

                    b.HasIndex("ModeloId");

                    b.ToTable("OrdenesProduccion", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Primera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Hora")
                        .HasColumnType("int");

                    b.Property<Guid?>("JornadaLaboralId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JornadaLaboralId");

                    b.ToTable("Primeras", (string)null);
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoraFin")
                        .HasColumnType("int");

                    b.Property<int>("HoraInicio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("WebControlShoes.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.OrdenProduccion", null)
                        .WithMany("Supervisores")
                        .HasForeignKey("OrdenProduccionId");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.OrdenProduccion", null)
                        .WithMany("Alertas")
                        .HasForeignKey("OrdenProduccionId");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Defecto", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.Incidencia", null)
                        .WithMany("Defectos")
                        .HasForeignKey("IncidenciaId");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Incidencia", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.JornadaLaboral", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("JornadaLaboralId");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.JornadaLaboral", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.OrdenProduccion", null)
                        .WithMany("JornadasLaborales")
                        .HasForeignKey("OrdenProduccionId");

                    b.HasOne("Zapatillas.Domain.Entities.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.OrdenProduccion", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.Colour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebControlShoes.Domain.Entities.LineaProduccion", "Linea")
                        .WithMany()
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zapatillas.Domain.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("Linea");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Primera", b =>
                {
                    b.HasOne("Zapatillas.Domain.Entities.JornadaLaboral", null)
                        .WithMany("ParesPrimera")
                        .HasForeignKey("JornadaLaboralId");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.Incidencia", b =>
                {
                    b.Navigation("Defectos");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.JornadaLaboral", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("ParesPrimera");
                });

            modelBuilder.Entity("Zapatillas.Domain.Entities.OrdenProduccion", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("JornadasLaborales");

                    b.Navigation("Supervisores");
                });
#pragma warning restore 612, 618
        }
    }
}
